{% set name = "SciToolsSciAnalysis" %}
{% set version = "2.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/SciToolsSciAnalysis-{{ version }}.tar.gz
  sha256: 294e3bd436076c63a3d6e5d91381d1281f6248c7fdac03c1fc91c639de167f4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - scipy

test:
  imports:
    - SciAnalysis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CFN-softbio/SciAnalysis
  summary: SciAnalysis scripts for processing image files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jklynch
